# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 049dab28631518b3d1740ca9f823db6d7c6bb89eb33003271dfc6472c614988851e26e4b2ea33f3a7615e6636cfe092c6e27f5e8933379f54070d76b7fd89331

test:
  secret_key_base: 1fb3d6180c81f25c0ade54603f7ff7a9e8d5573c27048c65539a492cc6a6b0ed1c7fb52124aa3ce545a792927256d5c95b740602baec409219865d3ebb74d67d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
